const f2Config = [
  {
    type: '定制、衣柜',
    color: '#ABDAB4',
    isSearchResult: false,
    content: [
      {
        num: 'B8006',
        name: '三力威',
        isClick: false,
        position: [['0.52', '0.41']],
      },
      {
        num: 'B8001',
        name: '京东定制',
        isClick: false,
        position: [['0.77', '0.50']],
      },
      {
        num: 'B8002',
        name: 'KD',
        isClick: false,
        position: [['0.67', '0.45']],
      },
      {
        num: 'B8003-1',
        name: '卡贝伯爵',
        isClick: false,
        position: [['0.64', '0.45']],
      },
      {
        num: 'B8109+B8110',
        name: '欧派',
        isClick: false,
        position: [['0.37', '0.43']],
      },
      {
        num: 'B8013',
        name: '威美',
        isClick: false,
        position: [['0.24', '0.30']],
      },
      {
        num: 'B8012',
        name: '志邦',
        isClick: false,
        position: [['0.32', '0.33']],
      },
      {
        num: 'B8105+8106',
        name: '德维尔',
        isClick: false,
        position: [['0.63', '0.54']],
      },
      {
        num: 'B8112',
        name: '米格',
        isClick: false,
        position: [['0.30', '0.41']],
      },
      {
        num: 'B8113',
        name: '伊博莱',
        isClick: false,
        position: [['0.28', '0.39']],
      },
      {
        num: 'B8209+B8210',
        name: 'DSC',
        isClick: false,
        position: [['0.35', '0.47']],
      },
      {
        num: 'B8319',
        name: '多丽',
        isClick: false,
        position: [['0.14', '0.49']],
      },
      {
        num: 'B8115',
        name: '索菲亚',
        isClick: false,
        position: [['0.25', '0.37']],
      },
      {
        num: 'B8010,',
        name: '百利玛',
        isClick: false,
        position: [['0.38', '0.35']],
      },
      {
        num: 'B8011,',
        name: '盼盼建筑',
        isClick: false,
        position: [['0.35', '0.33']],
      },
    ],
  },
  {
    type: '影音、灯饰、玻璃、硅藻泥',
    color: '#B1BD87',
    content: [
      {
        num: 'B8301',
        name: '超凡影音',
        isClick: false,
        position: [['0.85', '0.68']],
      },
      {
        num: 'B8216, B8321, B8322',
        name: '名佳',
        isClick: false,
        position: [['0.10', '0.45']],
      },
      {
        num: 'B8206',
        name: '玻璃先生',
        isClick: false,
        position: [['0.60', '0.59']],
      },
      {
        num: 'B8201',
        name: '兰舍',
        isClick: false,
        position: [['0.75', '0.64']],
      },
    ],
  },
  {
    type: '地板',
    color: '#D3E8CC',
    content: [
      {
        num: 'B8003-2',
        name: '安信',
        isClick: false,
        position: [['0.61', '0.45']],
      },
      {
        num: 'B8005',
        name: '大自然地板',
        isClick: false,
        position: [['0.56', '0.42']],
      },
      {
        num: 'B8101',
        name: '圣蝶',
        isClick: false,
        position: [['0.74', '0.58']],
      },
      {
        num: 'B8107+B8108',
        name: '圣狮',
        isClick: false,
        position: [['0.57', '0.51']],
      },
      {
        num: 'B8205',
        name: '欧洲之家',
        isClick: false,
        position: [['0.63', '0.59']],
      },
      {
        num: 'B8207+8208',
        name: '圣象',
        isClick: false,
        position: [['0.55', '0.56']],
      },
      {
        num: 'B8308',
        name: '威兹帕克',
        isClick: false,
        position: [['0.61', '0.70']],
      },
      {
        num: 'B8309',
        name: '生活家',
        isClick: false,
        position: [['0.56', '0.66']],
      },
      { num: 'B8308', name: '久盛', isClick: true, position: [[0.61, 0.71]] },
      {
        num: 'B8309',
        name: '威兹帕克',
        isClick: true,
        position: [[0.58, 0.69]],
      },
    ],
  },
  {
    type: '门、门窗',
    color: '#76D1C0',
    content: [
      {
        num: 'B8007',
        name: '春天',
        isClick: false,
        position: [['0.50', '0.40']],
      },
      {
        num: 'B8008',
        name: '西西',
        isClick: false,
        position: [['0.47', '0.39']],
      },
      {
        num: 'B8009',
        name: 'TATA',
        isClick: false,
        position: [['0.43', '0.38']],
      },
      {
        num: 'B8015',
        name: '伯鲁克',
        isClick: false,
        position: [['0.22', '0.29']],
      },
      {
        num: 'B8016',
        name: '千年舟',
        isClick: false,
        position: [['0.19', '0.29']],
      },
      {
        num: 'B8018',
        name: '森鹰',
        isClick: false,
        position: [['0.14', '0.38']],
      },
      {
        num: 'B8211',
        name: '龙甲',
        isClick: false,
        position: [['0.31', '0.46']],
      },
      {
        num: 'B8212',
        name: '屋里屋外',
        isClick: false,
        position: [['0.28', '0.45']],
      },
      {
        num: 'B8215',
        name: '墨瑟',
        isClick: false,
        position: [['0.22', '0.42']],
      },
      {
        num: 'B8306',
        name: '福人空间',
        isClick: false,
        position: [['0.68', '0.72']],
      },
      {
        num: 'B8310',
        name: '开开',
        isClick: false,
        position: [['0.48', '0.63']],
      },
      {
        num: 'B8311',
        name: '奥斯坦汀',
        isClick: false,
        position: [['0.44', '0.62']],
      },
      {
        num: 'B8312',
        name: '兔宝宝',
        isClick: false,
        position: [['0.41', '0.61']],
      },
      {
        num: 'B8313',
        name: '梵蒂斯',
        isClick: false,
        position: [['0.38', '0.59']],
      },
      {
        num: 'B8315',
        name: '美福',
        isClick: false,
        position: [['0.35', '0.57']],
      },
      {
        num: 'B8316',
        name: '王力',
        isClick: false,
        position: [['0.28', '0.55']],
      },
      {
        num: 'B8318',
        name: '沃盾',
        isClick: false,
        position: [['0.21', '0.50']],
      },
    ],
  },
  {
    type: '家装、楼梯',
    color: '#AFC7C6',
    content: [
      {
        num: 'B8102+B8103+B8202+B8203, B8302, B8303+B8305',
        name: '品尚艺墅',
        isClick: false,
        position: [
          [0.81, 0.75],
          [0.67, 0.56],
          [0.71, 0.57],
          [0.67, 0.6],
          [0.7, 0.61],
        ],
      },
      {
        num: 'B8017',
        name: '富豪',
        isClick: false,
        position: [['0.15', '0.34']],
      },
    ],
  },
]

export default f2Config
// module.exports = f2Config
